
# 1) Minimal SearXNG settings with JSON + DOI resolver bits
environment.etc."searxng/settings.yml".text = ''
use_default_settings: true

server:
  # generate:  openssl rand -hex 32
  secret_key: "CHANGE_ME_TO_RANDOM"

search:
  formats: [html, json]   # <- needed for Open WebUI

# ---- DOI resolver settings (required by SearXNG) ----
doi_resolvers:
  doi.org: "https://doi.org/"
  oadoi.org: "https://oadoi.org/"
  sci-hub.se: "https://sci-hub.se/"
default_doi_resolver: "doi.org"
'';
