return {
	"folke/trouble.nvim",
	cmd = "Trouble",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	opts = {
		focus = true,
		icons = {
			indent = {
				top = "│ ",
				middle = "├╴",
				last = "└╴",
				fold_open = "v ",
				fold_closed = "> ",
				ws = "  ",
			},
			folder_closed = "[+]",
			folder_open = "[-]",
			kinds = {
				Array = "arr ",
				Boolean = "bool ",
				Class = "cls ",
				Constant = "const ",
				Constructor = "ctor ",
				Enum = "enum ",
				EnumMember = "em ",
				Event = "evt ",
				Field = "fld ",
				File = "file ",
				Function = "fn ",
				Interface = "iface ",
				Key = "key ",
				Method = "fn ",
				Module = "mod ",
				Namespace = "ns ",
				Null = "null ",
				Number = "num ",
				Object = "obj ",
				Operator = "op ",
				Package = "pkg ",
				Property = "prop ",
				String = "str ",
				Struct = "struct ",
				TypeParameter = "type ",
				Variable = "var ",
			},
		},
	},
	keys = {
		{ "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", desc = "diagnostics (Trouble)" },
		{ "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "buffer diagnostics" },
		{ "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", desc = "symbols" },
		{ "<leader>xl", "<cmd>Trouble lsp toggle focus=false win.position=right<cr>", desc = "lsp definitions/refs" },
		{ "<leader>xL", "<cmd>Trouble loclist toggle<cr>", desc = "location list" },
		{ "<leader>xQ", "<cmd>Trouble qflist toggle<cr>", desc = "quickfix list" },
	},
}
