env:
  TERM: alacritty
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8
    
window:
  # Specified in floating number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.7
  title: terminal

font:
  normal:
    family: "Monofur Nerd Font"
    style: Medium
  size: 9.0

selection:
  save_to_clipboard: true

colors:
  primary:
    # hard contrast: background = '#1d2021'
    background: '#32302f'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black: '#282828'
    red: '#cc241d'
    green: '#98971a'
    yellow: '#d79921'
    blue: '#458588'
    magenta: '#b16286'
    cyan: '#689d6a'
    white: '#a89984'

  # Bright colors
  bright:
    black: '#928374'
    red: '#fb4934'
    green: '#b8bb26'
    yellow: '#fabd2f'
    blue: '#83a598'
    magenta: '#d3869b'
    cyan: '#8ec07c'
    white: '#ebdbb2'
theme: Gruvbox-Dark
