[language-server.astro-ls]
command = "pnpm"
args = ["astro-ls","--stdio"]
config = {typescript = {tsdk = "./node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = ["astro-ls" ]

